# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/no_avatar.jpg', upload_to='profile_images'),
        ),
    ]
