# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True)),
                ('answers', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('href', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
