# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antifu', '0002_auto_20180217_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1024)),
                ('loveliness', models.IntegerField()),
                ('burnfactor', models.IntegerField()),
                ('logicRating', models.IntegerField()),
                ('accuracyRating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=512)),
                ('tags', models.CharField(max_length=128)),
                ('grammarFail', models.IntegerField()),
                ('logicFail', models.IntegerField()),
                ('toxicity', models.IntegerField()),
                ('harmful', models.IntegerField()),
                ('report', models.IntegerField()),
                ('views', models.IntegerField()),
                ('picturePost', models.ImageField(upload_to='')),
                ('category', models.ManyToManyField(to='antifu.Category')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antifu.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('profileRef', models.ImageField(upload_to='')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antifu.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antifu.Post')),
            ],
        ),
    ]
