# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antifu', '0002_auto_20180217_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=1024)),
                ('loveliness', models.IntegerField(default=0)),
                ('burnfactor', models.IntegerField(default=0)),
                ('logicRating', models.IntegerField(default=0)),
                ('accuracyRating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('context', models.TextField(max_length=512)),
                ('tags', models.CharField(max_length=128)),
                ('grammarFail', models.IntegerField(default=0)),
                ('logicFail', models.IntegerField(default=0)),
                ('toxicity', models.IntegerField(default=0)),
                ('harmful', models.IntegerField(default=0)),
                ('report', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('picturePost', models.ImageField(upload_to='post_pictures')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antifu.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antifu.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antifu.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antifu.UserProfile'),
        ),
    ]
