# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifu', '0002_auto_20180217_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='_', unique=True),
            preserve_default=False,
        ),
    ]
