# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antifu', '0003_auto_20180321_1650'),
        ('antifu', '0002_auto_20180321_1725'),
    ]

    operations = [
    ]
