# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifu', '0003_auto_20180313_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsEmail',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=0)),
                ('from_email', models.TextField(default=0)),
                ('subject', models.TextField(default=0)),
                ('message', models.TextField(default=0)),
            ],
        ),
    ]
