# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifu', '0004_contactusemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusemail',
            name='from_email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactusemail',
            name='message',
            field=models.CharField(default=0, max_length=1024),
        ),
        migrations.AlterField(
            model_name='contactusemail',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactusemail',
            name='subject',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
