# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifu', '0005_auto_20180313_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusemail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
